### ISSUE TITLE
UI - Test that all user action works

### ISSUE THREAD

**Issue by johnsjulander** [Tunell/react#58]

**Comment by johnTunell** [comment]
Rapportera material funkar inte för vissa material:

https://drive.google.com/file/d/0BwHHSY4jS9mhTkxBYjhVMENObWM/view

**Comment by johnsjulander** [comment]
Rapportera material:

Material menyn i rapportera material spökar. Väljer inte det material som man klickar på:

https://drive.google.com/file/d/0BwHHSY4jS9mhNFdyTEJ4ODJXM2M/view

**Comment by johnsjulander** [comment]
Skapa byggdel:

Det material som är förvalt verkar inte ges någon enhet, vilket gör att submit crashar:

https://drive.google.com/file/d/0BwHHSY4jS9mhQzIxUmVHeFFmc2M/view

**Comment by johnsjulander** [comment]
Skapa byggdel:

Menyn spökar, väljer inte det material som man klickar på.
Väljer man "Välj material" kraschar det.

https://drive.google.com/file/d/0BwHHSY4jS9mhTWd4LXBiZGwwbmc/view
