### ISSUE TITLE
Bifoga byggvarudeklaration per byggdel. Lägga till i databas document, och used_material_has_document. Hosta på S3 storage. Document_references

### ISSUE THREAD

**Issue by Tunell** [Tunell/react#77]

**Comment by johnsjulander** [comment]
1. Lägg till table i databasen: DONE

document
id
name
url


object_has_document
object_id
table_name

2. Sätt upp en S3 instans för att förvara document DONE

Forstätt här: https://devcenter.heroku.com/articles/s3-upload-node

2.5 Kolla upp att filer läggs upp via bifoga filer html genom form-data. DONE

3. Lägg till endpoint i swagger:

Vad vill folk göra?

- Lägga upp ett dokument DONE
- Titta på sina upplagda dokument i en lista

- Associera ett dokument med ett used-material
- Associera ett dokument med ett composite-material
- Se vilket dokument som är associerat med en rad i used-material


- GET document/?user_id
- GET document/{id}
- POST document/
- DELETE document/{id}

4. Skriv controller för alla endpoints

5.  Skriv tester för samtliga endpoints i Postman

6.  Skriv tester för samtliga endpoints i Postman
