### ISSUE TITLE
Grundmaterial ska rapporteras med återvinningsgrad, composite utan

### ISSUE THREAD

**Issue by Tunell** [Tunell/react#79]

**Comment by Tunell** [comment]
Vi behöver en admin användare eller någon form av flaggning så att vissa composite-materials (de som är rå-material) visas för alla användare 
Dessa material är dessutom lite speciella eftersom man ska rapportera återvinningsgrad på de.

**Comment by johnsjulander** [comment]
Okej! Har skapat en admin user nu. Vadå, typ: återvinningsgrad 1, 2, 3, 4 ? Vi lär snacka om det

**Comment by johnsjulander** [comment]
Inte mandatory återvinningsgrad på used material, den är optional. Ändra swagger och db. Stål-1, stål-2, stål-3

**Comment by Tunell** [comment]
Vi behöver fixa något så att normala användare får fram compositeMaterials ifrån admin, typ:
http://localhost:3000/api/composite-materials?user_id=1&user_id=0
